server:
  port: 8200

spring:
  application:
    name: spring-provider

eureka:
  instance:
    instance-id: instanceId-${spring.application.name}
    prefer-ip-address: true
  client:
    serviceUrl:
      #Eureka Server的地址，注意：一定要有 /eureka/
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:6001}/eureka/